---
- name: Install nginx
  become: yes
  apt:
    name:
      - nginx
    state: present
    update_cache: yes
- name: Automatically start nginx when the server starts
  become: yes
  systemd:
    name: nginx
    enabled: yes
- name: Start nginx
  become: yes
  systemd:
    name: nginx
    state: started